Out of bound exeptions
evgeniyamelone/Java-Education-Course pull request #20
Opened 2020-06-14 10:03 UTC by evgeniyamelone

Task:  Write code to generate and catch an ArrayIndexOutOfBoundsException.

2020-06-20 15:01 UTC, mih-kopylov requested changes

2020-06-20 15:01 UTC, mih-kopylov commented on src/main/java/exceptions/ArrayActions.java
> +            System.out.println("\nElement with " + index + " is: ");
It's not quite readable to concatenate strings.
Better to use `String.format("Element with index %s is %", index, arr[index])`

2020-06-20 15:01 UTC, mih-kopylov commented on src/main/java/exceptions/ArrayActions.java
> +            System.out.println("Exeption: " + e);
will it be better to have `e.printStackTrace()` so that not only a message, but a stacktrase be printed as well?

2020-06-21 14:30 UTC, evgeniyamelone commented on src/main/java/exceptions/ArrayActions.java
> +            System.out.println("\nElement with " + index + " is: ");
Updated

2020-06-21 14:30 UTC, evgeniyamelone commented on src/main/java/exceptions/ArrayActions.java
> +            System.out.println("Exeption: " + e);
Updated

2020-06-25 14:48 UTC, ssheludchenko approved these changes

2020-07-02 15:13 UTC, merged